//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auditions.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditionLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditionLocation()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public byte AuditionLimit { get; set; }
        public string AuditionPhoto { get; set; }
        public string AuditionDetails { get; set; }
        public Nullable<System.DateTime> AuditionDate { get; set; }
        public bool IsActive { get; set; }
        public string LManagerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
