//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auditions.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int AuditionID { get; set; }
        public int ActorId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime AuditionDate { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual AuditionLocation AuditionLocation { get; set; }
    }
}
